### ISSUE TITLE
Outbrain SDK xcframework

### ISSUE THREAD

**Issue by atom2ueki** [outbrain/outbrain-iOS-Framework#1]
for the SDK Outbrain provided including multi architecture which is easy to develop but if manually import sdk when distribute will cause code signing issue.
<img width="745" alt="Screenshot 2021-01-05 at 11 38 57 AM" src="https://user-images.githubusercontent.com/5100535/103608131-9543e000-4f55-11eb-8625-b97b4e765bcc.png">
even though we can use script get through it
suggest either provide xcframework format or split architecture distribute the SDK.

**Comment by oded-regev** [comment]
Outbrain iOS SDK is distributed as XCFramework starting v4.2.0
