### ISSUE TITLE
Outbrain has UIWebView in the binary

### ISSUE THREAD

**Issue by nihp** [outbrain/outbrain-iOS-Framework#6]
I am getting the UIWebView error from the appstore. While grepping I have seen this framework has the UIWebView. Any updates on this.

If I use  the latest does it has any major changes for this in the implementation code?

Binary file project/Classes/OutbrainSDK.framework/OutbrainSDK matches

**Comment by AlonShprung** [comment]
Hi @nihp,
Which version of the SDK are you using? We are not using UIWebView in our SDK.

**Comment by nihp** [comment]
@AlonShprung I mean while grep the UIWebView I got a binary file has the UIWebView. Not sure does this make the app to reject.

I can't able to find the version. I am using the OutbrainSDK.framework (around on 12/9/13). But unable to find the version.

**Comment by AlonShprung** [comment]
@nihp 
Please update to our latest SDK
